frr version 10.4.1
frr defaults traditional
log syslog informational
log facility local4
agentx
zebra nexthop-group keep 1
fpm address 127.0.0.1
no fpm use-next-hop-groups
service integrated-vtysh-config
!
password zebra
enable password zebra
!
hostname spine12
!
interface Loopback0
 ip router isis CORE
 isis passive
!
interface Ethernet0
 ip router isis CORE
 isis network point-to-point
 isis circuit-type level-2-only
!
interface Ethernet4
 ip router isis CORE
 isis network point-to-point
 isis circuit-type level-2-only
!
router isis CORE
 net 49.0001.0000.0000.0022.00
 is-type level-2-only
 metric-style wide
 lsp-gen-interval 1
 spf-interval 1
 segment-routing on
 segment-routing global-block 16000 23999
 segment-routing node-msd 8
 segment-routing prefix 22.22.22.22/32 index 22
!
ip nht resolve-via-default
ipv6 nht resolve-via-default
!
