frr version 10.4.1
frr defaults traditional
hostname leaf12
log syslog informational
log facility local4
agentx
zebra nexthop-group keep 1
fpm address 127.0.0.1
no fpm use-next-hop-groups
service integrated-vtysh-config
!
password zebra
enable password zebra
!
ip route 1.1.1.1/32 192.168.20.3 250
ip route 1.1.1.1/32 192.168.22.3 250
ip route 192.168.10.2/32 192.168.20.3 250
!
vrf Vrf_BLUE
 ip nht resolve-via-default
 ipv6 nht resolve-via-default
exit-vrf
!
vrf Vrf_RED
 ip nht resolve-via-default
 ipv6 nht resolve-via-default
exit-vrf
!
interface Ethernet0
 ip router isis CORE
 isis circuit-type level-2-only
 isis network point-to-point
exit
!
interface Ethernet4
 ip router isis CORE
 isis circuit-type level-2-only
 isis network point-to-point
exit
!
interface Loopback0
 ip router isis CORE
 isis passive
exit
!
router bgp 65000
 bgp router-id 2.2.2.2
 no bgp ebgp-requires-policy
 neighbor 192.168.10.2 remote-as 65000
 !
 address-family ipv4 vpn
  neighbor 192.168.10.2 activate
 exit-address-family
exit
!
router bgp 65000 vrf Vrf_BLUE
 bgp router-id 2.2.2.2
 !
 address-family ipv4 unicast
  redistribute connected
  label vpn export auto
  rd vpn export 2.2.2.2:110
  nexthop vpn export 2.2.2.2
  rt vpn both 65000:110
  export vpn
  import vpn
 exit-address-family
exit
!
router bgp 65000 vrf Vrf_RED
 bgp router-id 2.2.2.2
 !
 address-family ipv4 unicast
  redistribute connected
  label vpn export auto
  rd vpn export 2.2.2.2:200
  nexthop vpn export 2.2.2.2
  rt vpn both 65000:200
  export vpn
  import vpn
 exit-address-family
exit
!
router isis CORE
 is-type level-2-only
 net 49.0001.0000.0000.0002.00
 lsp-timers gen-interval 1 refresh-interval 900 max-lifetime 1200
 segment-routing on
 segment-routing node-msd 8
 segment-routing prefix 2.2.2.2/32 index 2
exit
!
ip nht resolve-via-default
!
ipv6 nht resolve-via-default
!
segment-routing
 traffic-eng
 exit
exit
!
